//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATURALLIFE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    public partial class HOME
    {
        public string ID { get; set; }

        public string TUADE1 { get; set; }
        public string TUADE2 { get; set; }
        public string TUADE3 { get; set; }
        public string TENNUT { get; set; }
        [DisplayName("Upload File")]
        public string HINHANHNEN { get; set; }

        public HttpPostedFileBase HINHANHNENFile { get; set; }
    }
}
