//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATURALLIFE.Models
{
    using System;
    using System.Collections.Generic;

    public partial class LIENHE
    {
        public string ID { get; set; }
        public string TUADE { get; set; }
        public string HOTLINE { get; set; }
        public string ADDRESSS { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string WEB { get; set; }
        public string EMAIL { get; set; }
        public string TUADECHANTRANG { get; set; }
    }
}
