//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATURALLIFE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BAULEPROFOLIOEntities2 : DbContext
    {
        public BAULEPROFOLIOEntities2()
            : base("name=BAULEPROFOLIOEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHANTRANG> CHANTRANGs { get; set; }
        public virtual DbSet<DSKHACHHANG> DSKHACHHANGs { get; set; }
        public virtual DbSet<HOME> HOMEs { get; set; }
        public virtual DbSet<LIENHE> LIENHEs { get; set; }
        public virtual DbSet<LOGOKHACHHANG> LOGOKHACHHANGs { get; set; }
        public virtual DbSet<MUCLINK> MUCLINKs { get; set; }
        public virtual DbSet<PHOTO> Photos { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THELOAITHUVIEN> THELOAITHUVIENs { get; set; }
        public virtual DbSet<THELOAITINTUC> THELOAITINTUCs { get; set; }
        public virtual DbSet<THUVIENANH> THUVIENANHs { get; set; }
        public virtual DbSet<TINTUC> TINTUCs { get; set; }
        public virtual DbSet<TRANGMODEL> TRANGMODELs { get; set; }
    }
}
