//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATURALLIFE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUCLINK
    {
        public string ID { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string LINKFB { get; set; }
        public string LINKPRIN { get; set; }
        public string LINKTWI { get; set; }
        public string LINKINS { get; set; }
        public string LINKYB { get; set; }
        public string LINKINK { get; set; }
    }
}
