//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATURALLIFE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    public partial class THUVIENANH
    {
        public string ID { get; set; }

        public string IDTHELOAI { get; set; }

        public virtual THELOAITHUVIEN THELOAITHUVIEN { get; set; }
        [DisplayName("Upload File")]

        public string HINHANH { get; set; }

        public HttpPostedFileBase HINHANHFile { get; set; }
    }
}
